spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/huffon?serverTimezone=Asia/Seoul
    username: root
    password: sk624853!
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5Dialect
  h2:
    console:
      enabled: false
      path: /console
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false